import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./globals.css";
import { WalletProvider } from "./context/WalletContext";
import { QRCodeProvider } from "./context/QRCodeContext";
import { EventProvider } from "./context/EventContext";

export const metadata: Metadata = {
  title: "EthiTix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <WalletProvider>
          <QRCodeProvider>
            <EventProvider>
              <Navbar />
              {children}
              <Footer />
            </EventProvider>
          </QRCodeProvider>
        </WalletProvider>
      </body>
    </html>
  );
}
